# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-26 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('number_1', models.IntegerField(db_column='1')),
                ('number_2', models.IntegerField(db_column='2')),
                ('number_3', models.IntegerField(blank=True, db_column='3', null=True)),
                ('number_4', models.IntegerField(blank=True, db_column='4', null=True)),
                ('number_5', models.IntegerField(blank=True, db_column='5', null=True)),
                ('number_6', models.IntegerField(blank=True, db_column='6', null=True)),
                ('number_7', models.IntegerField(blank=True, db_column='7', null=True)),
                ('number_8', models.IntegerField(blank=True, db_column='8', null=True)),
                ('number_9', models.IntegerField(blank=True, db_column='9', null=True)),
                ('number_10', models.IntegerField(blank=True, db_column='10', null=True)),
            ],
            options={
                'db_table': 'choice',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('theme', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('count', models.IntegerField()),
                ('is_single', models.IntegerField()),
                ('id_description', models.IntegerField()),
            ],
            options={
                'db_table': 'vote',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VoteDescription',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('answer1', models.CharField(max_length=100)),
                ('answer2', models.CharField(max_length=100)),
                ('answer3', models.CharField(blank=True, max_length=100, null=True)),
                ('answer4', models.CharField(blank=True, max_length=100, null=True)),
                ('answer5', models.CharField(blank=True, max_length=100, null=True)),
                ('answer6', models.CharField(blank=True, max_length=100, null=True)),
                ('answer7', models.CharField(blank=True, max_length=100, null=True)),
                ('answer8', models.CharField(blank=True, max_length=100, null=True)),
                ('answer9', models.CharField(blank=True, max_length=100, null=True)),
                ('answer10', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'vote_description',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VoteInformation',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('id_vote', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('id_choice', models.IntegerField()),
                ('ip', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'vote_information',
                'managed': False,
            },
        ),
    ]
